CREATE OR REPLACE TRIGGER EMAIL_ID_TRG
BEFORE INSERT ON EMAIL_NOTIFICATION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT EMAIL_NOTIFICATION_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
END;
/
------------------------------------------------
CREATE OR REPLACE TRIGGER EMAIL_AFTER_INSERT_TRG
AFTER INSERT ON EMAIL_NOTIFICATION
FOR EACH ROW
BEGIN
    SEND_EMAIL_REQUEST(:NEW.ID);
END;
/
